format_version: 10
pipelines:
  nodejs-app:
    group: nodejs
    label_template: ${COUNT}
    lock_behavior: lockOnFailure
    materials:
      git:
        git: https://github.com/bhavyastar/example-app-check
        branch: master
        shallow_clone: true
    rules:
      - allow: refer
        pipeline_group: nodejs
    stages:
      - build:
          jobs:
            build:
              tasks:
                - exec:
                    command: npm
                    arguments:
                      - install
                - exec:
                    command: npm
                    arguments:
                      - test
                - exec:
                    command: npm
                    arguments:
                      - run
                      - build
      - deploy:
          jobs:
            deploy:
              tasks:
                - exec:
                    command: npm
                    arguments:
                      - run
                      - deploy
